#Data Wrangling with Pandas

[Aj. NesT the Series](http://bit.ly/ajnesttheseriesSubscribe)

Referenence: [Pyhton Data Cleaning Cookbook 2020](https://github.com/PacktPublishing/Python-Data-Cleaning-Cookbook)

##Practice 1: เช็คคุณภาพข้อมูลและทำความสะอาดข้อมูล

Measuring Data Quality and Data Cleaning of Your Data 

##Workshop 3: การเลือกแถว
--> Selecting Rows

###Input Datasets

* **[nls97.csv](https://drive.google.com/file/d/1-av28HdgEAYPc7ZSmvIh1JdR6Pb4HIfg/view?usp=sharing)** - the National Longitudinal Survey (NLS) 1997-2017.

####Question 3: เราจะสำรวจวิธีการเลือกแถว Zoom In Zoom Out ข้อมูล

**STEP 1:** นำเข้า Datasets โดยทำการ Upload ไฟล์ nls97.csv และไฟล์ covidtotals.csv ขึ้น Google Colab (ไฟล์นี้จะถูกลบเมื่อเราหลุดจาก Session หรือปิด Browser) หรือ Python IDE เช่น PyCharm, VSCode, Juputer Notebook, etc.

**STEP 2:** ทำการอ่านไฟล์ .csv ด้วย pandas เก็บเป็น Dataframe

ใช้คำสั่ง .read_csv()

**STEP 3:** ตั้งค่าและแสดง index และ size ของ nls97 data

ใช้คำสั่ง set_index()

**STEP 4:** ตั้งค่าและแสดง index และ size ของ nls97 data

ใช้คำสั่ง set_index()

**STEP 5:** แสดงจำนวน data types และ non-null value

ใช้คำสั่ง info()

In [ ]:
import pandas as pd
import numpy as np
nls97 = pd.read_csv("/content/nls97.csv")
nls97.set_index("personid", inplace=True)
print(nls97)
print(nls97.info())

          gender  birthmonth  ...      colenrfeb17      colenroct17
personid                      ...                                  
100061    Female           5  ...  1. Not enrolled  1. Not enrolled
100139      Male           9  ...  1. Not enrolled  1. Not enrolled
100284      Male          11  ...  1. Not enrolled  1. Not enrolled
100292      Male           4  ...              NaN              NaN
100583      Male           1  ...  1. Not enrolled  1. Not enrolled
...          ...         ...  ...              ...              ...
999291    Female           4  ...  1. Not enrolled  1. Not enrolled
999406      Male           7  ...  1. Not enrolled  1. Not enrolled
999543    Female           8  ...  1. Not enrolled  1. Not enrolled
999698    Female           5  ...  1. Not enrolled  1. Not enrolled
999963    Female           9  ...  1. Not enrolled  1. Not enrolled

[8984 rows x 88 columns]
<class 'pandas.core.frame.DataFrame'>
Int64Index: 8984 entries, 100061 to 999963
Data colu

**STEP 6:** ทำการเลือก row เริ่มที่แถว 1001 ไปถึงแถว 1004

Use slicing to select a few rows

[1000:1004] เนื่องจาก index เริ่มต้นที่ 0 => [เลขแถวเริ่มต้น-1: เลขแถวปลายทาง]

In [ ]:
print(nls97[1000:1004]) #ให้ทดลองเปิดไฟล์ .csv ในโปรแกรม Excel จะอยู่ที่บรรทัด 1002 - 1005

          gender  birthmonth  ...      colenrfeb17      colenroct17
personid                      ...                                  
195884      Male          12  ...              NaN              NaN
195891      Male           9  ...  1. Not enrolled  1. Not enrolled
195970    Female           3  ...  1. Not enrolled  1. Not enrolled
195996    Female           9  ...              NaN              NaN

[4 rows x 88 columns]


**STEP 7:** ทำการ Transport กลับ rows เป็น columns กลับ columns เป็น rows

ใช้คำสั่ง .T Transport เพื่อให้เห็นรายละเอียดของข้อมูลมากขึ้น

In [ ]:
print(nls97[1000:1004].T)

personid              195884           195891           195970  195996
gender                  Male             Male           Female  Female
birthmonth                12                9                3       9
birthyear               1981             1980             1982    1980
highestgradecompleted    NaN               12               17     NaN
maritalstatus            NaN    Never-married    Never-married     NaN
...                      ...              ...              ...     ...
colenroct15              NaN  1. Not enrolled  1. Not enrolled     NaN
colenrfeb16              NaN  1. Not enrolled  1. Not enrolled     NaN
colenroct16              NaN  1. Not enrolled  1. Not enrolled     NaN
colenrfeb17              NaN  1. Not enrolled  1. Not enrolled     NaN
colenroct17              NaN  1. Not enrolled  1. Not enrolled     NaN

[88 rows x 4 columns]


**STEP 8:** ทำการเลือก rows แบบกระโดดข้ามแถวระหว่างทาง

Use slicing to start at the 1001st row and go to the 1004th row, skipping every
other row.

ใช้คำสั่ง [เลขแถวเริ่มต้น-1 : เลขแถวปลายทาง : ช่วงแถวที่ข้าม]

In [ ]:
print(nls97[1000:1004:2].T) #ข้ามไป step ละ 2 แถว เช่น 1 -> 3 

personid              195884           195970
gender                  Male           Female
birthmonth                12                3
birthyear               1981             1982
highestgradecompleted    NaN               17
maritalstatus            NaN    Never-married
...                      ...              ...
colenroct15              NaN  1. Not enrolled
colenrfeb16              NaN  1. Not enrolled
colenroct16              NaN  1. Not enrolled
colenrfeb17              NaN  1. Not enrolled
colenroct17              NaN  1. Not enrolled

[88 rows x 2 columns]


**STEP 9:** ทำการเลือก 3 rows แรก ที่อยู่บนสุด

Select the first three rows using head and [ ] operator slicing

ใช้คำสั่ง [: n] n คือจำนวนแถวบนสุด ผลลัพธ์เหมือนกับคำสั่ง .head()

In [ ]:
#select first 3 rows using head() and Python slicing
print(nls97.head(3).T)
print(nls97[:3].T) #ใช้ [: ] ผลลัพธ์เหมือนกับคำสั่ง .head()

personid                        100061           100139           100284
gender                          Female             Male             Male
birthmonth                           5                9               11
birthyear                         1980             1983             1984
highestgradecompleted               13               12                7
maritalstatus                  Married          Married    Never-married
...                                ...              ...              ...
colenroct15            1. Not enrolled  1. Not enrolled  1. Not enrolled
colenrfeb16            1. Not enrolled  1. Not enrolled  1. Not enrolled
colenroct16            1. Not enrolled  1. Not enrolled  1. Not enrolled
colenrfeb17            1. Not enrolled  1. Not enrolled  1. Not enrolled
colenroct17            1. Not enrolled  1. Not enrolled  1. Not enrolled

[88 rows x 3 columns]
personid                        100061           100139           100284
gender                      

**STEP 10:** ทำการเลือก 3 rows ล่างสุด 

Select the last three rows using tail and [ ] operator slicing

ใช้คำสั่ง [-n: ] n คือ จำนวนแถวล่างสุด ผลลัพธ์เหมือนกับคำสั่ง .tail() 

In [ ]:
#select last 3 rows using tail() and Python slicing
print(nls97.tail(3).T)
print(nls97[-3:].T) #ใช้ [-n: ] ผลลัพธ์เหมือนกับคำสั่ง .tail()

personid                        999543           999698           999963
gender                          Female           Female           Female
birthmonth                           8                5                9
birthyear                         1984             1983             1982
highestgradecompleted               12               12               17
maritalstatus                 Divorced    Never-married          Married
...                                ...              ...              ...
colenroct15            1. Not enrolled  1. Not enrolled  1. Not enrolled
colenrfeb16            1. Not enrolled  1. Not enrolled  1. Not enrolled
colenroct16            1. Not enrolled  1. Not enrolled  1. Not enrolled
colenrfeb17            1. Not enrolled  1. Not enrolled  1. Not enrolled
colenroct17            1. Not enrolled  1. Not enrolled  1. Not enrolled

[88 rows x 3 columns]
personid                        999543           999698           999963
gender                      

**STEP 11:** ทำการเลือกค่าข้อมูล values ของ rows ด้วยคำสั่ง .loc 

Select a few rows using the loc data accessor

ใช้คำสั่ง .loc[ index_values ] ในที่นี้คือค่าที่อยู่ในแถวของ personid ซึ่งตั้งเป็น index]

เช่น ต้องการค่าข้อมูลแถวของ personalid (เนื่องจากเป็น index) ที่ 195884, 195891, 195970

In [ ]:
print(nls97.loc[[195884,195891,195970]].T) # , เลือกแบบค่าที่ต้องการ

personid              195884           195891           195970
gender                  Male             Male           Female
birthmonth                12                9                3
birthyear               1981             1980             1982
highestgradecompleted    NaN               12               17
maritalstatus            NaN    Never-married    Never-married
...                      ...              ...              ...
colenroct15              NaN  1. Not enrolled  1. Not enrolled
colenrfeb16              NaN  1. Not enrolled  1. Not enrolled
colenroct16              NaN  1. Not enrolled  1. Not enrolled
colenrfeb17              NaN  1. Not enrolled  1. Not enrolled
colenroct17              NaN  1. Not enrolled  1. Not enrolled

[88 rows x 3 columns]


In [ ]:
print(nls97.loc[195884:195970].T) # : เลือกแบบจากเริ่มต้นถึงปลายทาง

personid              195884           195891           195970
gender                  Male             Male           Female
birthmonth                12                9                3
birthyear               1981             1980             1982
highestgradecompleted    NaN               12               17
maritalstatus            NaN    Never-married    Never-married
...                      ...              ...              ...
colenroct15              NaN  1. Not enrolled  1. Not enrolled
colenrfeb16              NaN  1. Not enrolled  1. Not enrolled
colenroct16              NaN  1. Not enrolled  1. Not enrolled
colenrfeb17              NaN  1. Not enrolled  1. Not enrolled
colenroct17              NaN  1. Not enrolled  1. Not enrolled

[88 rows x 3 columns]


**STEP 12:** ทำการเลือกแบบค่าตำแหน่ง index ของแถวเพื่อเข้าถึงค่าข้อมูล values ด้วยคำสั่ง .iloc 

Select a few rows from the beginning of the DataFrame with the iloc data accessor

ใช้คำสั่ง .iloc[ index_numbers ] ในที่นี้คือค่าตำแหน่งแถวของ personid ซึ่งตั้งเป็น index]

In [ ]:
print(nls97.iloc[[0,1,2]].T) #เข้าถึงแถวด้านบน นับจากบนลงล่าง
print(nls97.iloc[[-3,-2,-1]].T) #เข้าถึงแถวจากด้านล่าง -1 คืออยู่ล่างสุด นับจากล่างขึ้นบน

personid                        100061           100139           100284
gender                          Female             Male             Male
birthmonth                           5                9               11
birthyear                         1980             1983             1984
highestgradecompleted               13               12                7
maritalstatus                  Married          Married    Never-married
...                                ...              ...              ...
colenroct15            1. Not enrolled  1. Not enrolled  1. Not enrolled
colenrfeb16            1. Not enrolled  1. Not enrolled  1. Not enrolled
colenroct16            1. Not enrolled  1. Not enrolled  1. Not enrolled
colenrfeb17            1. Not enrolled  1. Not enrolled  1. Not enrolled
colenroct17            1. Not enrolled  1. Not enrolled  1. Not enrolled

[88 rows x 3 columns]
personid                        999543           999698           999963
gender                      

**STEP 13:** ทำการเลือกหลาย rows ตามเงื่อนไขด้วย boolean indexing

Select multiple rows conditionally

**โจทย์** 

สร้าง DataFrame ของบุคคลที่นอนหลับ ใช้ข้อมูลของคอลัมน์ nightlyhrssleep 

โดยพิจาณาค่า Quantile ประมาณ 5% พบว่านอนหลับประมาณ 4 ชั่วโมง 

ของผู้ตอบแบบสำรวจทั้งหมด 6,706 คน

ลองทดสอบว่าใครนอนหลับ 4 ชั่วโมงหรือน้อยกว่า

ด้วย nls97 nightlyhrssleep<=4 

ซึ่งสร้างชุดค่า True (<=4) และ False (!<=4) ของ  pandas ที่เรากำหนดให้กับ sleepcheckbool

In [ ]:
print(nls97.nightlyhrssleep.quantile(0.05))  #ทดสอบใช้สถิติ quantile 5% พบว่าได้ 4 ชั่วโมง 
print(nls97.nightlyhrssleep.count())         #นับจำนวนผู้คอบแบบสำรวจทั้งหมดในคอลัมน์นี้ พบว่าได้ 6706 คน
sleepcheckbool = nls97.nightlyhrssleep<=4    #สร้างเงื่อนไข ว่าใครนอนหลับ 4 ชั่วโมงหรือน้อยกว่านั้น
print(sleepcheckbool)                        #แสดงคนที่นอนหลับ 4 ชั่วโมงหรือน้อยกว่านั้น
sleepcheckbool.to_csv("/content/sleepcheckbool") #ถ้า True แสดงว่านอนหลับ <= 4 ชั่วโมง
lowsleep = nls97.loc[sleepcheckbool] #ใช้ข้อมูล nls97 แล้ว Filter ข้อมูล sleepcheckbool(<=4)เก็บใน lowsleep
print(lowsleep.shape)                #ข้อมูลมี 364 rows 88 columns
lowsleep.to_csv("/content/lowsleep") #แสดงข้อมูล lowsleep ที่รวมข้อมูล nls97 โดย Filer sleepcheckbool 

4.0
6706
personid
100061    False
100139    False
100284    False
100292    False
100583    False
          ...  
999291    False
999406    False
999543    False
999698    False
999963    False
Name: nightlyhrssleep, Length: 8984, dtype: bool
(364, 88)


**STEP 14:** ทำการเลือก rows ตามหลายเงื่อนไข

Select rows based on multiple conditions

ใช้คำสั่ง .describe() หาค่าสถิติเบื้องต้นของทุก colums ใน DataFrame

**โจทย์**

ผู้ที่นอนน้อยจะมีจำนวนบุตรที่บ้านอยู่กี่คน

ใช้ Python อธิบายเพื่อให้เข้าใจถึงการแจกแจงจำนวนบุตรของผู้ที่นอน <= 4 ชั่วโมง

สร้าง DataFrame ใหม่กับคนที่มี nightlyhrsleep <= 4 ชั่วโมง และมีจำนวนลูกที่บ้าน >= 3 คนขึ้นไป


In [ ]:
print(lowsleep.childathome.describe())  #ในที่นี้เราจะดูของคอลัมน์ childathome ที่อยู่ภายในชุดข้อมูลของ lowsleep
lowsleep3pluschildren = nls97.loc[(nls97.nightlyhrssleep<=4) & (nls97.childathome>=3)] #สร้างเงื่อนไขขึ้น
print(lowsleep3pluschildren.shape) #แสดงจำนวน rows และ colums
print(lowsleep3pluschildren)       #แสดงข้อมูล
lowsleep3pluschildren.to_csv("/content/lowsleep3pluschildren") #Export เป็นไฟล์เพิ่มนามสกุล .csv เปิด excel

count    293.000000
mean       1.788396
std        1.400685
min        0.000000
25%        1.000000
50%        2.000000
75%        3.000000
max        9.000000
Name: childathome, dtype: float64
(82, 88)
          gender  birthmonth  ...        colenrfeb17        colenroct17
personid                      ...                                      
119754    Female           6  ...    1. Not enrolled    1. Not enrolled
141531    Female          11  ...    1. Not enrolled    1. Not enrolled
152706      Male           7  ...    1. Not enrolled    1. Not enrolled
156823    Female          12  ...    1. Not enrolled    1. Not enrolled
158355    Female           7  ...    1. Not enrolled    1. Not enrolled
...          ...         ...  ...                ...                ...
905774      Male           6  ...    1. Not enrolled    1. Not enrolled
907315    Female           1  ...    1. Not enrolled    1. Not enrolled
955166      Male          12  ...    1. Not enrolled    1. Not enrolled
95610

**STEP 15:** เลือก rows และ columns ตามหลายเงื่อนไข

Select rows based on multiple conditions and also select columns

In [ ]:
updatelowsleep3pluschildren = nls97.loc[(nls97.nightlyhrssleep<=4) & (nls97.childathome>=3),
                                  ['nightlyhrssleep','childathome']]   #เลือกเฉพาะ Columns ที่ต้องการ
print(updatelowsleep3pluschildren)  #แสดงข้อมูล
updatelowsleep3pluschildren.to_csv("/content/updatelowsleep3pluschildren") #Export เป็นไฟล์.csv

          nightlyhrssleep  childathome
personid                              
119754                4.0          4.0
141531                4.0          5.0
152706                4.0          4.0
156823                1.0          3.0
158355                4.0          4.0
...                   ...          ...
905774                4.0          3.0
907315                4.0          3.0
955166                3.0          3.0
956100                4.0          6.0
991756                4.0          3.0

[82 rows x 2 columns]
